; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.7"

; Modules
projects[ctools][version] = "1.x-dev"

projects[calendar][version] = "3.x-dev"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
projects[cmtls][download][type] = "git"
projects[cmtls][download][url] = "https://communitytools@github.com/communitytools/Community-Tools-Core.git"
projects[cmtls][type] = "module"
projects[cmtls][version] = "2.0-alpha1"

projects[context][version] = "3.0-beta1"

projects[date][version] = "2.x-dev"

projects[entity][version] = "1.0-beta10"

projects[features_extra][version] = "1.x-dev"

projects[features][version] = "1.0-beta3"

projects[gmap][version] = "1.x-dev"

projects[location][version] = "3.x-dev"

projects[menu_block][version] = "2.2"

projects[menu_node][version] = "1.1"

projects[references][version] = "2.0-beta3"

projects[og][version] = "1.0"

projects[strongarm][version] = "2.0-beta2"

projects[views][version] = "3.0-rc1"
